sudo: required

language: python

python:
#  - "2.7"
  - "3.6"
  - "3.7"

matrix:
  include:
    - os: linux-ppc64le
      services:
      - docker
    - os: linux
      services:
      - docker
    - os: osx
      osx_image: xcode9.4
      language: generic

install: ./script/travis/install

script:
  - ./script/travis/ci
  - ./script/travis/build-binary

#before_deploy:
#  - "./script/travis/render-bintray-config.py < ./script/travis/bintray.json.tmpl > ./bintray.json"

#deploy:
#  provider: bintray
#  user: docker-compose-roleuser
#  key: '$BINTRAY_API_KEY'
#  file: ./bintray.json
#  skip_cleanup: true
#  on:
#    all_branches: true
