#!/bin/bash

set -e

# tox -- tests/unit
ARCH=$(uname -m)

if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    if [[ "$ARCH" == "ppc64le" ]]; then
        tox -e py27,py37 -- tests/unit
    else
        #tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .) -- tests/unit
        tox -e py27,py37 -- tests/unit
    fi
else
    tox -e py27,py36,py37 -- tests/unit
fi
