#!/bin/bash

set -e

if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    tox -e py36 -- tests/unit
elif [[ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]]; then
    tox -e py36 -- tests/unit
else
    tox -e py36 -- tests/unit
fi
