#!/bin/bash

set -ex

ARCH=$(uname -m)

if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    if [[ "$ARCH" == "ppc64le" ]]; then
        sudo pip install --upgrade pip tox==2.1.1 virtualenv
        pip --version
    else
        pip install tox==2.1.1
    fi
else
    sudo pip install --upgrade pip tox==2.1.1 virtualenv
    pip --version
fi
