#!/bin/bash

set -ex

if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    pip install tox==2.1.1
elif [[ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]]; then
    sudo pip install --upgrade pip tox==2.1.1 virtualenv
    pip --version
else
    sudo pip install --upgrade pip tox==2.1.1 virtualenv
    pip --version
fi
